#----------------------------------------------------------------------------*
#                                                                            *
# C    H E L L O W O R L D    F O R    M I N G W 3 2    O N    M A C O S X   *
#                                                                            *
#   Updated for Release 2                                                    *
#                                                                            *
#----------------------------------------------------------------------------*

TOOL_DIR := /usr/local/gcc-4.8.0-qt-4.8.4-for-mingw32/win32-gcc/bin

SOURCES = $(reb2sac_SOURCES)

reb2sac_SOURCES = absolute_activation_inhibition_generation_method.c \
	absolute_inhibition_generation_method.c abs_phage_lambda2_simulation_run_termination_decider.c \
	abs_phage_lambda_simulation_run_termination_decider.c abstraction_engine.c abstraction_method_manager.c \
	abstraction_reporter.c back_end_processor.c birth_death_generation_method2.c \
	birth_death_generation_method3.c birth_death_generation_method4.c birth_death_generation_method5.c \
	birth_death_generation_method6.c birth_death_generation_method7.c birth_death_generation_method.c \
	bunker_monte_carlo.c compartment_manager.c reaction_manager.c \
	confidence_interval_stop_rule.c critical_concentration_finder.c critical_level_finder.c \
	critical_level_order_decider.c csv_simulation_printer.c ctmc_analysis_back_end_processor.c \
	ctmc_analyzer.c ctmc_stationary_analysis_back_end_processor.c \
	ctmc_stationary_analyzer.c ctmc_transformation_checker.c default_reb2sac_properties.c \
	default_simulation_run_termination_decider.c default_ts_species_level_updater.c \
	degradation_stoichiometry_amplifier2.c degradation_stoichiometry_amplifier3.c \
	degradation_stoichiometry_amplifier4.c degradation_stoichiometry_amplifier5.c \
	degradation_stoichiometry_amplifier6.c degradation_stoichiometry_amplifier7.c \
	degradation_stoichiometry_amplifier8.c degradation_stoichiometry_amplifier.c dependency_graph.c \
	dimerization_reduction_level_assignment.c dimerization_reduction_method.c dimer_to_monomer_substitution_method.c \
	dot_back_end_processor.c ode_simulation.c embedded_runge_kutta_fehlberg_method.c \
	embedded_runge_kutta_prince_dormand_method.c emc_leaked_stationary_analyzer.c emc_simulation.c \
	emc_stationary_analyzer.c ppta_method.c enzyme_kinetic_qssa_method.c enzyme_kinetic_rapid_equilibrium_method2.c \
	enzyme_kinetic_rapid_equilibrium_method.c euler_method.c \
	final_state_generation_method.c \
	flat_phage_lambda2_simulation_run_termination_decider.c flat_phage_lambda_simulation_run_termination_decider.c \
	front_end_processor.c gillespie_monte_carlo.c monte_carlo.c \
	gnuplot_dat_simulation_printer.c hash_table.c hse2_back_end_processor.c hse_back_end_processor.c \
	hse_back_end_processor_util.c hse_logical_statement_handler.c hse_transformation_checker.c \
	implicit_gear1_method.c implicit_gear2_method.c implicit_runge_kutta_4_method.c \
	inducer_structure_transformation_method.c ir2ctmc_transformer.c ir2xhtml_transformer.c IR.c ir_node.c \
	irrelevant_species_elimination_method.c kinetic_law.c kinetic_law_constants_simplifier.c \
	kinetic_law_evaluater.c kinetic_law_find_next_time.c kinetic_law_support.c law_of_mass_action_util.c linked_list.c log.c logical_species_node.c \
	main.c marginal_probability_density_evolution_monte_carlo.c markov_analysis_result_reporter.c markov_chain.c \
	max_concentration_reaction_adder.c modifier_constant_propagation_abstraction_method.c \
	modifier_structure_transformation_method.c multiple_products_reaction_elimination_method.c \
	multiple_reactants_reaction_elimination_method.c nary_level_back_end_process2.c nary_level_back_end_process.c \
	nary_order_decider.c nary_order_unary_transformation_method2.c \
	nary_order_unary_transformation_method3.c nary_order_unary_transformation_method.c next_reaction_simulation.c \
	normal_waiting_time_monte_carlo.c null_simulation_printer.c \
	op_site_binding_abstraction_method2.c op_site_binding_abstraction_method3.c \
	op_site_binding_abstraction_method.c pow_kinetic_law_transformer.c random_number_generator.c reaction_node.c \
	reb2sac.c reversible_reaction_structure_transformation_method.c \
	distribute_method.c reversible_to_irreversible_transformation_method.c rnap_operator_binding_abstraction_method.c \
	sac_phage_lambda_simulation_run_termination_decider.c sbml_back_end_processor.c sbml_front_end_processor.c sbml_symtab.c \
	similar_reaction_combining_method.c simulation_printer.c simulation_run_termination_decider.c \
	single_reactant_product_reaction_elimination_method.c species_critical_level.c species_critical_level_generator.c \
	species_node.c ssa_with_user_update.c stoichiometry_amplifier2.c \
	stoichiometry_amplifier3.c stoichiometry_amplifier.c stop_flag_generation_method.c strconv.c \
	symtab.c tsd_simulation_printer.c ts_species_level_updater.c \
	type_1_pili1_simulation_run_termination_decider.c type_1_pili2_simulation_run_termination_decider.c \
	type1pili_gillespie_ci.c type_1_pili_markov_analysis_result_reporter.c \
	function_manager.c constraint_manager.c event_manager.c rule_manager.c unit_manager.c util.c vector.c xhtml_back_end_processor.c \
	analysis_def_parser.tab.c sad_ast.c sad_ast_func_registry.c sad_ast_pretty_printer.c \
	sad_ast_exp_evaluator.c sad_ast_creator.c sad_simulation_run_termination_decider.c \
	analysis_def_scanner.c constraint_simulation_run_termination_decider.c

OBJECTS_DIR := objects
EXECUTABLE := reb2sac.exe
INCLUDE_DIR := ../../include

ALL_OBJECT_FILES := $(patsubst %, $(OBJECTS_DIR)/%.o, $(SOURCES))

all:$(OBJECTS_DIR) $(EXECUTABLE)

#--- Make object dir
$(OBJECTS_DIR):
	mkdir $(OBJECTS_DIR)

#--- C compiling : use gcc
$(OBJECTS_DIR)/%.c.o:%.c
	$(TOOL_DIR)/i586-mingw32-gcc -I$(INCLUDE_DIR) -DNAME_FOR_ID -DWINDOWS -D__MINGW32__ -c $< -o $@

#--- C link : use gcc
$(EXECUTABLE):$(ALL_OBJECT_FILES)
	$(TOOL_DIR)/i586-mingw32-gcc $^ -o $@ -L../win/lib -L../../bin -lcygwin1 -lm -lgsl -lgslcblas -lsbml
	$(TOOL_DIR)/i586-mingw32-strip --strip-all $@

clean:
	rm -f $(EXECUTABLE)
	rm -Rf $(OBJECTS_DIR)/
